name: icaleg
version: 1.0.8+8
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^5.0.0
  http: ^1.0.0
  get_storage: ^2.1.1
  package_info_plus: ^4.0.2
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.3
  ionicons: ^0.2.2
  flutter_svg: ^2.0.7
  image_picker: ^0.8.9
  pinput: ^2.3.0
  bottom_navy_bar: ^6.0.0
  lottie: ^2.5.0
  # google_ml_kit: ^0.16.2
  nik_validator: ^1.1.2
  mnc_identifier_ocr: ^1.0.20
  geolocator: ^10.0.0
  intl: ^0.18.1
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.14
  graphic: ^2.2.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  

dev_dependencies: 
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/