name: icaleg
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^5.0.0
  http: ^1.0.0
  get_storage: ^2.1.1
  package_info_plus: ^4.0.2
  connectivity_plus: ^4.0.1
  ionicons: ^0.2.2
  flutter_svg: ^2.0.7
  image_picker: ^0.8.9
  pinput: ^2.3.0

dev_dependencies: 
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
